import Foundation
import IOKit
import IOKit.hid
import CoreGraphics

// ============================================================
// Xiaomi Pad Pen -> macOS mouse click compensation
//
// HID format observed:
//
//   Digitizer page 0x0D:
//     0x30 = Tip Pressure   0...8191
//     0x42 = Tip Switch
//     0x32 = In Range
//
//   Generic Desktop page 0x01:
//     0x30 = X
//     0x31 = Y
//
// Main idea:
//
//   HID decides stroke lifetime.
//
//   pressure > 0 || tip == true
//       => stroke starts
//
//   pressure == 0 && tip == false
//       => stroke ends
//
// Once a stroke starts, pressure changes NEVER cause mouseUp.
// ============================================================


// ------------------------------------------------------------
// Device
// ------------------------------------------------------------

let TARGET_VENDOR_ID = 6353
let TARGET_PRODUCT_ID = 11525


// ------------------------------------------------------------
// Tuning
// ------------------------------------------------------------

// Delay before releasing mouse after HID says:
// pressure == 0 && tip == false
//
// A tiny delay protects against transient zero-pressure packets.
let RELEASE_DELAY: TimeInterval = 0.015

// Xiaomi sends a bogus coordinate after the pen leaves range:
//
//     X = 0
//     Y = 32767
//
// Suppress pointer motion briefly around that packet.
let LEAVE_FREEZE_TIME: TimeInterval = 0.15

// Enable verbose debugging.
let DEBUG_HID = false
let DEBUG_MOUSE = false


// ------------------------------------------------------------
// Synthetic-event marker
// ------------------------------------------------------------

// Used so our CGEventTap can recognize events generated by this script.
let SYNTHETIC_TAG: Int64 = 0x5849414F4D495045 // "XIAOMIPE"


// ------------------------------------------------------------
// Global HID state
// ------------------------------------------------------------

var hidPressure: Int64 = 0
var hidTip = false

var hidX: Int64 = 0
var hidY: Int64 = 0

var haveHIDX = false
var haveHIDY = false

var hidInRange = false


// ------------------------------------------------------------
// Stroke state
// ------------------------------------------------------------

var strokeActive = false

// True when WE generated the mouseDown and therefore must eventually
// generate its matching mouseUp.
var syntheticMouseDownActive = false

// Used to invalidate delayed mouseUp callbacks.
var releaseGeneration: UInt64 = 0


// ------------------------------------------------------------
// Cursor/freezing state
// ------------------------------------------------------------

var lastGoodCursorPosition = CGPoint.zero
var haveLastGoodCursorPosition = false

var freezePointerUntil: CFAbsoluteTime = 0


// ============================================================
// Utilities
// ============================================================

func debug(_ text: String) {
    if DEBUG_HID || DEBUG_MOUSE {
        print(text)
    }
}


func currentTime() -> CFAbsoluteTime {
    return CFAbsoluteTimeGetCurrent()
}


func pointerFrozen() -> Bool {
    return currentTime() < freezePointerUntil
}


// ============================================================
// Synthetic mouse events
// ============================================================

func postSyntheticMouseEvent(
    type: CGEventType,
    position: CGPoint
) {
    guard let event = CGEvent(
        mouseEventSource: nil,
        mouseType: type,
        mouseCursorPosition: position,
        mouseButton: .left
    ) else {
        print("Failed to create synthetic CGEvent")
        return
    }

    event.setIntegerValueField(
        .eventSourceUserData,
        value: SYNTHETIC_TAG
    )

    event.post(tap: .cghidEventTap)
}


func syntheticMouseDown() {
    guard !syntheticMouseDownActive else {
        return
    }

    let position: CGPoint

    if haveLastGoodCursorPosition {
        position = lastGoodCursorPosition
    } else if let event = CGEvent(source: nil) {
        position = event.location
    } else {
        return
    }

    syntheticMouseDownActive = true

    if DEBUG_MOUSE {
        print(
            "SYNTH DOWN pressure=\(hidPressure) tip=\(hidTip) " +
            "pos=(\(Int(position.x)),\(Int(position.y)))"
        )
    }

    postSyntheticMouseEvent(
        type: .leftMouseDown,
        position: position
    )
}


func syntheticMouseUp() {
    guard syntheticMouseDownActive else {
        return
    }

    let position: CGPoint

    if haveLastGoodCursorPosition {
        position = lastGoodCursorPosition
    } else if let event = CGEvent(source: nil) {
        position = event.location
    } else {
        return
    }

    // Change state BEFORE posting the event.
    syntheticMouseDownActive = false

    if DEBUG_MOUSE {
        print(
            "SYNTH UP pressure=\(hidPressure) tip=\(hidTip) " +
            "pos=(\(Int(position.x)),\(Int(position.y)))"
        )
    }

    postSyntheticMouseEvent(
        type: .leftMouseUp,
        position: position
    )
}


// ============================================================
// Stroke state machine
// ============================================================

func beginStrokeIfNeeded() {

    // Any real contact with the digitizer starts the stroke.
    //
    // DO NOT use arbitrary thresholds such as pressure < 500.
    //
    // We deliberately cover the entire range.
    let touching = hidTip || hidPressure > 0

    guard touching else {
        return
    }

    // Cancel any pending delayed release.
    releaseGeneration &+= 1

    if !strokeActive {
        strokeActive = true

        if DEBUG_HID {
            print(
                "=== STROKE BEGIN === " +
                "pressure=\(hidPressure) tip=\(hidTip)"
            )
        }
    }

    // Important:
    //
    // We always establish the mouse-down state ourselves at the
    // beginning of the stroke. We do NOT hand it back to macOS when
    // pressure becomes large.
    syntheticMouseDown()
}


func scheduleStrokeEndIfNeeded() {

    // The pen isn't really released until BOTH are false.
    //
    // We observed:
    //
    // Tip=1 Pressure=138
    // Tip=1 Pressure=0
    // Tip=0 Pressure=0
    //
    // Therefore pressure == 0 alone MUST NOT end a stroke.
    guard hidPressure == 0 && !hidTip else {
        return
    }

    guard strokeActive else {
        return
    }

    releaseGeneration &+= 1

    let myGeneration = releaseGeneration

    DispatchQueue.main.asyncAfter(
        deadline: .now() + RELEASE_DELAY
    ) {
        guard myGeneration == releaseGeneration else {
            return
        }

        // Check again after debounce.
        guard hidPressure == 0 && !hidTip else {
            return
        }

        guard strokeActive else {
            return
        }

        strokeActive = false

        if DEBUG_HID {
            print("=== STROKE END ===")
        }

        syntheticMouseUp()
    }
}


func updateStrokeState() {

    if hidTip || hidPressure > 0 {
        beginStrokeIfNeeded()
    } else {
        scheduleStrokeEndIfNeeded()
    }
}


// ============================================================
// Xiaomi out-of-range coordinate handling
// ============================================================

func checkForInvalidPenCoordinate() {

    guard haveHIDX && haveHIDY else {
        return
    }

    // Packet observed from the tablet when the pen leaves detection:
    //
    // raw:
    // 03 08 00 00 FF 7F 00 00 00 00
    //
    // X = 0
    // Y = 32767
    //
    let invalidCoordinate =
        hidX == 0 &&
        hidY >= 32760 &&
        hidPressure == 0 &&
        !hidTip

    guard invalidCoordinate else {
        return
    }

    if DEBUG_HID {
        print(
            "PEN LEFT RANGE: invalid coordinate " +
            "X=\(hidX) Y=\(hidY)"
        )
    }

    // Suppress the short burst of bogus macOS pointer motion.
    freezePointerUntil = currentTime() + LEAVE_FREEZE_TIME

    // If macOS already moved the pointer because of the invalid packet,
    // snap it back to the last valid position.
    if haveLastGoodCursorPosition {
        CGWarpMouseCursorPosition(lastGoodCursorPosition)
    }
}


// ============================================================
// HID callback
// ============================================================

let hidValueCallback: IOHIDValueCallback = {
    context,
    result,
    sender,
    value
    in

    let element = IOHIDValueGetElement(value)

    let page = IOHIDElementGetUsagePage(element)
    let usage = IOHIDElementGetUsage(element)

    let intValue = IOHIDValueGetIntegerValue(value)

    // --------------------------------------------------------
    // Digitizer page
    // --------------------------------------------------------

    if page == 0x0D {

        switch usage {

        // Tip Pressure
        case 0x30:
            hidPressure = Int64(intValue)

            if DEBUG_HID {
                print(
                    "HID Pressure = \(hidPressure)"
                )
            }

            updateStrokeState()


        // In Range
        case 0x32:
            hidInRange = intValue != 0


        // Tip Switch
        case 0x42:
            hidTip = intValue != 0

            if DEBUG_HID {
                print(
                    "HID Tip = \(hidTip ? 1 : 0)"
                )
            }

            updateStrokeState()


        default:
            break
        }

        return
    }


    // --------------------------------------------------------
    // Generic Desktop
    // --------------------------------------------------------

    if page == 0x01 {

        switch usage {

        // X
        case 0x30:
            hidX = Int64(intValue)
            haveHIDX = true

            checkForInvalidPenCoordinate()


        // Y
        case 0x31:
            hidY = Int64(intValue)
            haveHIDY = true

            checkForInvalidPenCoordinate()


        default:
            break
        }
    }
}


// ============================================================
// CGEvent tap
// ============================================================

let eventTapCallback: CGEventTapCallBack = {
    proxy,
    type,
    event,
    refcon
    in

    // Event tap may be disabled by timeout.
    if type == .tapDisabledByTimeout ||
       type == .tapDisabledByUserInput {

        if let tap = refcon {
            let port = Unmanaged<CFMachPort>
                .fromOpaque(tap)
                .takeUnretainedValue()

            CGEvent.tapEnable(
                tap: port,
                enable: true
            )
        }

        return Unmanaged.passUnretained(event)
    }


    // --------------------------------------------------------
    // Never interfere with our own generated events.
    // --------------------------------------------------------

    let userData = event.getIntegerValueField(
        .eventSourceUserData
    )

    if userData == SYNTHETIC_TAG {
        return Unmanaged.passUnretained(event)
    }


    let position = event.location


    // --------------------------------------------------------
    // Block Xiaomi's bogus "pen left screen" motion.
    // --------------------------------------------------------

    if pointerFrozen() {

        switch type {

        case .mouseMoved,
             .leftMouseDragged,
             .rightMouseDragged,
             .otherMouseDragged:

            if DEBUG_MOUSE {
                print(
                    "BLOCK invalid pointer move " +
                    "pos=(\(Int(position.x)),\(Int(position.y)))"
                )
            }

            // Keep the pointer exactly at its last valid position.
            if haveLastGoodCursorPosition {
                CGWarpMouseCursorPosition(
                    lastGoodCursorPosition
                )
            }

            return nil


        default:
            break
        }
    }


    // --------------------------------------------------------
    // Native mouseDown while our synthetic down is active
    // --------------------------------------------------------
    //
    // Xiaomi/macOS may eventually generate its own down once the
    // pressure becomes sufficiently large.
    //
    // Do NOT allow a second mouseDown into the application.
    //
    // More importantly:
    //
    // DO NOT release our synthetic state here.
    //
    // That old "handoff" behaviour is what created the pressure
    // transition dead zone.
    // --------------------------------------------------------

    if type == .leftMouseDown {

        lastGoodCursorPosition = position
        haveLastGoodCursorPosition = true

        if strokeActive && syntheticMouseDownActive {

            if DEBUG_MOUSE {
                print(
                    "SUPPRESS native LEFT_DOWN " +
                    "pressure=\(hidPressure)"
                )
            }

            return nil
        }

        return Unmanaged.passUnretained(event)
    }


    // --------------------------------------------------------
    // Native mouseUp
    // --------------------------------------------------------
    //
    // During an active HID stroke, native macOS is NOT allowed
    // to terminate the stroke.
    //
    // HID owns stroke lifetime.
    // --------------------------------------------------------

    if type == .leftMouseUp {

        lastGoodCursorPosition = position
        haveLastGoodCursorPosition = true

        if strokeActive {

            if DEBUG_MOUSE {
                print(
                    "SUPPRESS native LEFT_UP " +
                    "pressure=\(hidPressure) tip=\(hidTip)"
                )
            }

            return nil
        }

        return Unmanaged.passUnretained(event)
    }


    // --------------------------------------------------------
    // Real native drag
    // --------------------------------------------------------

    if type == .leftMouseDragged {

        lastGoodCursorPosition = position
        haveLastGoodCursorPosition = true

        return Unmanaged.passUnretained(event)
    }


    // --------------------------------------------------------
    // Mouse move
    // --------------------------------------------------------
    //
    // Critical for drawing:
    //
    // Some Xiaomi packets arrive at macOS as mouseMoved even though
    // we have already synthetically pressed the left button.
    //
    // If left as mouseMoved, drawing applications only see:
    //
    //      start ----------------> end
    //
    // Convert it into leftMouseDragged for the duration of the stroke.
    // --------------------------------------------------------

    if type == .mouseMoved {

        lastGoodCursorPosition = position
        haveLastGoodCursorPosition = true

        if strokeActive {

            event.type = .leftMouseDragged

            if DEBUG_MOUSE {
                print(
                    "MOVE -> DRAG " +
                    "pressure=\(hidPressure) " +
                    "pos=(\(Int(position.x)),\(Int(position.y)))"
                )
            }

            return Unmanaged.passUnretained(event)
        }

        return Unmanaged.passUnretained(event)
    }


    return Unmanaged.passUnretained(event)
}


// ============================================================
// Find Xiaomi HID device
// ============================================================

let manager = IOHIDManagerCreate(
    kCFAllocatorDefault,
    IOOptionBits(kIOHIDOptionsTypeNone)
)


let matching: [String: Any] = [
    kIOHIDVendorIDKey: TARGET_VENDOR_ID,
    kIOHIDProductIDKey: TARGET_PRODUCT_ID
]

IOHIDManagerSetDeviceMatching(
    manager,
    matching as CFDictionary
)


// ============================================================
// HID setup
// ============================================================

IOHIDManagerRegisterInputValueCallback(
    manager,
    hidValueCallback,
    nil
)

IOHIDManagerScheduleWithRunLoop(
    manager,
    CFRunLoopGetCurrent(),
    CFRunLoopMode.defaultMode.rawValue
)

let openResult = IOHIDManagerOpen(
    manager,
    IOOptionBits(kIOHIDOptionsTypeNone)
)

if openResult != kIOReturnSuccess {
    print(
        "Warning: IOHIDManagerOpen returned \(openResult)"
    )
}


// ============================================================
// Confirm device
// ============================================================

if let devicesCF = IOHIDManagerCopyDevices(manager) {

    let devices = devicesCF as NSSet

    if devices.count == 0 {
        print(
            """
            Xiaomi Pad 9 Pro Max HID device not found.

            Expected:
              VendorID  = \(TARGET_VENDOR_ID)
              ProductID = \(TARGET_PRODUCT_ID)
            """
        )

        exit(1)
    }

    print("Found HID device:")

    for case let device as IOHIDDevice in devices {

        let product =
            IOHIDDeviceGetProperty(
                device,
                kIOHIDProductKey as CFString
            )

        let vendor =
            IOHIDDeviceGetProperty(
                device,
                kIOHIDVendorIDKey as CFString
            )

        let productID =
            IOHIDDeviceGetProperty(
                device,
                kIOHIDProductIDKey as CFString
            )

        print("  Product: \(product ?? "?" as CFTypeRef)")
        print("  VendorID: \(vendor ?? "?" as CFTypeRef)")
        print("  ProductID: \(productID ?? "?" as CFTypeRef)")
    }

} else {
    print("Unable to enumerate HID devices.")
    exit(1)
}


// ============================================================
// Event tap setup
// ============================================================

let eventMask =
    (CGEventMask(1) << CGEventType.leftMouseDown.rawValue) |
    (CGEventMask(1) << CGEventType.leftMouseUp.rawValue) |
    (CGEventMask(1) << CGEventType.leftMouseDragged.rawValue) |
    (CGEventMask(1) << CGEventType.mouseMoved.rawValue) |
    (CGEventMask(1) << CGEventType.rightMouseDragged.rawValue) |
    (CGEventMask(1) << CGEventType.otherMouseDragged.rawValue)


guard let eventTap = CGEvent.tapCreate(
    tap: .cgSessionEventTap,
    place: .headInsertEventTap,
    options: .defaultTap,
    eventsOfInterest: eventMask,
    callback: eventTapCallback,
    userInfo: nil
) else {

    print(
        """
        Failed to create CGEvent tap.

        Please enable Accessibility permission for Terminal:

        System Settings
          -> Privacy & Security
          -> Accessibility
          -> Terminal

        Then restart Terminal and run the script again.
        """
    )

    exit(1)
}


// ------------------------------------------------------------
// The callback needs the event tap so that it can re-enable
// itself after a timeout.
//
// Because CGEvent.tapCreate() doesn't let us change userInfo later,
// create a second tap using the first tap's opaque pointer.
// ------------------------------------------------------------

// The event tap itself does not normally time out with this workload,
// so we can simply enable it here. tapDisabledByTimeout handling above
// is retained as a harmless safeguard.

let runLoopSource = CFMachPortCreateRunLoopSource(
    kCFAllocatorDefault,
    eventTap,
    0
)

CFRunLoopAddSource(
    CFRunLoopGetCurrent(),
    runLoopSource,
    .commonModes
)

CGEvent.tapEnable(
    tap: eventTap,
    enable: true
)


// ============================================================
// Start
// ============================================================

print()
print("Xiaomi pen click compensation running.")
print()
print("Behaviour:")
print("  HID contact       -> immediate mouseDown")
print("  any pressure      -> keep stroke alive")
print("  Pressure=0 Tip=0 -> mouseUp")
print("  mouseMoved        -> drag while drawing")
print("  X=0 Y=32767       -> suppress corner jump")
print()
print("Ctrl-C to stop.")
print()


CFRunLoopRun()